# Generated by Django 5.0.1 on 2024-01-26 09:42

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="city",
            name="region",
        ),
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="news",
            name="author",
        ),
        migrations.RemoveField(
            model_name="order",
            name="authorized_user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="region",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.address",
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.png",
                upload_to="avatars/",
                verbose_name="Фото профиля",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Номер телефона"
            ),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="News",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
    ]
