# Generated by Django 5.0.1 on 2024-01-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_order_address_remove_city_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=18, unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
