version: '3.3'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env
    restart: always

  backend:
    build: .
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    restart: always

  nginx:
    build: ../nginx
    env_file: .env
    ports:
      - ${NGINX_HOST_PORT}:80
    volumes:
      - media:/media/
      - static:/usr/share/nginx/html/
    depends_on:
      - backend
    restart: always