version: '3.8'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env
    restart: always

  celery:
    image: smintank/kdsstroy_backend
    command: celery -A kds_stroy worker --loglevel=info
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - backend
      - redis
    restart: always

  redis:
    image: redis:latest
    restart: always

  backend:
    image: smintank/kdsstroy_backend
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
      - redis
    restart: always

  nginx:
    image: smintank/kdsstroy_gateway
    env_file: .env
    ports:
      - ${NGINX_HOST_PORT}:80
    volumes:
      - media:/media/
      - static:/usr/share/nginx/html/
    depends_on:
      - backend
    restart: always