# Generated by Django 5.0.8 on 2025-01-19 11:00

import django.core.validators
import django.db.models.deletion
import orders.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=orders.utils.get_upload_path, verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "фото заказа",
                "verbose_name_plural": "Фото заказов",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField(verbose_name="Номер заказа")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "phone_number",
                    models.CharField(max_length=18, verbose_name="Номер телефона"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Зарегистрирован", "🟥 Зарегистрирован"),
                            ("В работе", "🟨 В работе"),
                            ("Завершен", "🟩 Завершен"),
                            ("Отменен", "⬛️ Отменен"),
                        ],
                        default="Зарегистрирован",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "cost",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10000000.0),
                        ],
                        verbose_name="Стоимость в руб.",
                    ),
                ),
                (
                    "final_cost",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10000000.0),
                        ],
                        verbose_name="Итог в руб.",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Скидка в %",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Адрес"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.city",
                        verbose_name="Населенный пункт",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
