# Generated by Django 5.0.1 on 2024-06-28 06:05

import django.core.validators
import django.db.models.deletion
import orders.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_district_shown",
                    models.BooleanField(default=True, verbose_name="Показывать район?"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Отображать"),
                ),
                (
                    "latitude",
                    models.FloatField(default=45.03333, verbose_name="Широта"),
                ),
                (
                    "longitude",
                    models.FloatField(default=38.98333, verbose_name="Долгота"),
                ),
            ],
            options={
                "verbose_name": "населенный пункт",
                "verbose_name_plural": "Населенные пункты",
            },
        ),
        migrations.CreateModel(
            name="CityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "тип населенного пункта",
                "verbose_name_plural": "Типы населенных пунктов",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "район",
                "verbose_name_plural": "Районы",
            },
        ),
        migrations.CreateModel(
            name="OrderPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=orders.utils.get_upload_path, verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "фото заказа",
                "verbose_name_plural": "Фото заказов",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "регион",
                "verbose_name_plural": "Регионы",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.city"
                    ),
                ),
            ],
            options={
                "verbose_name": "адрес",
                "verbose_name_plural": "Адреса",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.citytype",
                verbose_name="Тип",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.district",
                verbose_name="Район",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField(verbose_name="Номер заказа")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "phone_number",
                    models.CharField(max_length=18, verbose_name="Номер телефона"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Зарегистрирован", "🟥 Зарегистрирован"),
                            ("В работе", "🟨 В работе"),
                            ("Завершен", "🟩 Завершен"),
                            ("Отменен", "⬛️ Отменен"),
                        ],
                        default="Зарегистрирован",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "cost",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10000000.0),
                        ],
                        verbose_name="Стоимость в руб.",
                    ),
                ),
                (
                    "final_cost",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10000000.0),
                        ],
                        verbose_name="Итог в руб.",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Скидка в %",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Адрес"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.city",
                        verbose_name="Населенный пункт",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
