# Generated by Django 5.0.1 on 2024-04-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Зарегистрирован", "Зарегистрирован"),
                    ("В работе", "В работе"),
                    ("Завершен", "Завершен"),
                    ("Отменен", "Отменен"),
                ],
                default="Зарегистрирован",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
