# Generated by Django 5.0.1 on 2024-04-09 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="region",
        ),
        migrations.AddField(
            model_name="city",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="city",
            name="is_district_shown",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="city",
            name="latitude",
            field=models.FloatField(default=45.03333),
        ),
        migrations.AddField(
            model_name="city",
            name="longitude",
            field=models.FloatField(default=38.98333),
        ),
        migrations.AddField(
            model_name="city",
            name="type",
            field=models.CharField(default="город", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.city",
                verbose_name="Населенный пункт",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.region"
                    ),
                ),
            ],
            options={
                "verbose_name": "район",
                "verbose_name_plural": "Районы",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="district",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.district",
            ),
        ),
    ]
