# Generated by Django 5.0.1 on 2024-04-09 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_city_region_city_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.district"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="type",
            field=models.CharField(max_length=255),
        ),
    ]
