# Generated by Django 5.0.1 on 2024-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_citytype_district_short_name_alter_city_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citytype",
            name="name",
            field=models.CharField(default="город", max_length=255),
        ),
        migrations.AlterField(
            model_name="citytype",
            name="short_name",
            field=models.CharField(max_length=255),
        ),
    ]
