# Generated by Django 5.0.1 on 2024-04-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_citytype_name_alter_citytype_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citytype",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="district",
            name="short_name",
            field=models.CharField(max_length=255),
        ),
    ]
