# Generated by Django 5.0.1 on 2024-04-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_telegramadminnotification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TelegramAdminNotification",
        ),
    ]
