# Generated by Django 5.0.1 on 2024-05-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_delete_telegramadminnotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cost",
            field=models.IntegerField(default=0, verbose_name="Итоговая стоимость"),
        ),
    ]
