# Generated by Django 5.0.1 on 2024-05-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_order_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="final_cost",
            field=models.IntegerField(default=0, verbose_name="Итоговая стоимость"),
        ),
        migrations.AlterField(
            model_name="order",
            name="cost",
            field=models.IntegerField(default=0, verbose_name="Стоимость"),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.IntegerField(default=0, verbose_name="Скидка в %"),
        ),
    ]
