# Generated by Django 5.0.1 on 2024-05-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cost",
            field=models.FloatField(default=0.0, verbose_name="Стоимость"),
        ),
        migrations.AlterField(
            model_name="order",
            name="final_cost",
            field=models.FloatField(default=0.0, verbose_name="Итоговая стоимость"),
        ),
    ]
