# Generated by Django 5.0.1 on 2024-05-01 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_alter_order_cost_alter_order_final_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cost",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10000000.0),
                    django.core.validators.DecimalValidator(10, 2),
                ],
                verbose_name="Стоимость в руб.",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Скидка в %",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="final_cost",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100000000.0),
                    django.core.validators.DecimalValidator(10, 2),
                ],
                verbose_name="Итог в руб.",
            ),
        ),
    ]
