# Generated by Django 5.0.1 on 2024-05-01 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_alter_order_cost_alter_order_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cost",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10000000.0),
                ],
                verbose_name="Стоимость в руб.",
            ),
        ),
    ]
