# Generated by Django 5.0.1 on 2024-05-01 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_alter_order_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="final_cost",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10000000.0),
                ],
                verbose_name="Итог в руб.",
            ),
        ),
    ]
