# Generated by Django 5.0.1 on 2024-06-03 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_alter_order_final_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.district",
                verbose_name="Район",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Отображать"),
        ),
        migrations.AlterField(
            model_name="city",
            name="is_district_shown",
            field=models.BooleanField(default=True, verbose_name="Показывать район?"),
        ),
        migrations.AlterField(
            model_name="city",
            name="latitude",
            field=models.FloatField(default=45.03333, verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="city",
            name="longitude",
            field=models.FloatField(default=38.98333, verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="city",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.citytype",
                verbose_name="Тип",
            ),
        ),
    ]
