# Generated by Django 5.0.1 on 2024-05-20 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="published_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
