# Generated by Django 5.0.1 on 2024-05-20 09:35

import django.db.models.deletion
import django.utils.timezone
import orders.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_published_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть публикацию.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.",
                        unique=True,
                        verbose_name="Идентификатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.RemoveField(
            model_name="news",
            name="photo",
        ),
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
        ),
        migrations.AlterField(
            model_name="news",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Снимите галочку, чтобы скрыть публикацию.",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="published_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата и время публикации",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.category",
                verbose_name="Категория",
            ),
        ),
        migrations.CreateModel(
            name="NewsPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to=orders.utils.get_upload_path)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_photos",
                        to="news.news",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="news",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="news_photos", to="news.newsphoto"
            ),
        ),
    ]
