# Generated by Django 5.0.1 on 2024-05-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_category_remove_news_photo_alter_news_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="photos",
            field=models.ManyToManyField(
                related_name="news_photos", to="news.newsphoto"
            ),
        ),
    ]
