# Generated by Django 5.0.1 on 2024-05-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_newsphoto_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="photos",
        ),
    ]
