# Generated by Django 5.0.1 on 2024-05-20 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_remove_news_photos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsphoto",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="news.news",
            ),
        ),
    ]
