# Generated by Django 5.0.1 on 2024-02-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="photo",
        ),
        migrations.AddField(
            model_name="order",
            name="cost",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Итоговая стоимость"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.IntegerField(default=0, verbose_name="Скидка"),
        ),
        migrations.AddField(
            model_name="order",
            name="is_discount",
            field=models.BooleanField(default=False, verbose_name="Скидка"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.IntegerField(verbose_name="Номер заказа"),
        ),
        migrations.CreateModel(
            name="OrderPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="order_photos", verbose_name="Фото"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
            options={
                "verbose_name": "фото заявки",
                "verbose_name_plural": "Фото заявок",
            },
        ),
    ]
