# Generated by Django 5.0.8 on 2024-09-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneverification",
            name="attempts_amount",
            field=models.IntegerField(
                default=0, max_length=100, verbose_name="Количество попыток"
            ),
        ),
    ]
