# Generated by Django 5.0.8 on 2024-09-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_phoneverification_attempts_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneverification",
            name="attempts_amount",
            field=models.IntegerField(default=0, verbose_name="Количество попыток"),
        ),
    ]
