# Generated by Django 5.0.1 on 2024-05-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_notify_user_tg_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_notify",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если пользователь должен получать уведомления о новых заказах",
                verbose_name="Уведомлять о новых заказах",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите Telegram ID в формате 123456789",
                max_length=50,
                verbose_name="Telegram",
            ),
        ),
    ]
