# Generated by Django 5.0.1 on 2024-03-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_phoneverificationrequest_phoneverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number_change_date",
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name="Последняя дата изменения номера телефона",
            ),
            preserve_default=False,
        ),
    ]
