# Generated by Django 5.0.8 on 2024-09-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_phoneverification_attempts_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Адрес"
            ),
        ),
    ]
