# Generated by Django 5.0.1 on 2024-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_phone_number_change_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneverification",
            name="pincode",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Пин-код"
            ),
        ),
    ]
