# Generated by Django 5.0.1 on 2024-03-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_phoneverification_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneverification",
            name="last_call",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время последнего запроса звонка"
            ),
        ),
    ]
